### ISSUE TITLE
Error when running LFQ data

### ISSUE THREAD

**Issue by RaquelVaya** [Nesvilab/FragPipe-Analyst-doc#45]
There is any possibility of a relative cuantification and doing a heatmap in case of having just one replicate of each sample? How can I fix this to achieve the report without errors like: 
- Error in evaluating the argument 'x' in selecting a method for function 'nrow': No finite residual standard deviations
- No finite residual standard deviations

Thanks

Raquel

**Comment by hsiaoyi0504** [comment]
@RaquelIQS Thanks for the question. We didn't set any limitation of replicates, so should be fine for just one replicate for each condition.

Looks like the error message you got is related to the differential expression analysis. Do you have a more detailed information about your dataset?

**Comment by RaquelVaya** [comment]
Hi @hsiaoyi0504,

Thank you for your comment, and I apologize for the delayed response. I have three samples of proteins that were attached to nanoparticles. These nanoparticles differ in their composition, so there should be differences in the proteins attached to them (the nanoparticles were incubated in a blood sample). All the samples were processed simultaneously. My idea is to use a heatmap to visualize the differences, like a relative quantification. I can provide you any metadata you need. I'm quite new to this field and entirely self-taught so thank you for the patient and the information.

Raquel

**Comment by RaquelVaya** [comment]
Im going to keep an eye on this chat. I have already send you some .tsv by email too.

**Comment by hsiaoyi0504** [comment]
@RaquelIQS Can you send the email again? I couldn't really find it.

**Comment by RaquelVaya** [comment]
Done, but I think it happens because of the replicates (n = 1)

**Comment by RaquelVaya** [comment]
Im doing the same with more replicates and there is still an error. I didnt touch the combined protein or the annotation sample file.

**Comment by RaquelVaya** [comment]
Hi @hsiao,

Thanks for the support. I try to analyze this data but there is a problem
that I can't solve by myself. Do you need something else?

best regards,

Raquel

[image: image.png]

**Comment by hsiaoyi0504** [comment]
@RaquelIQS I still don't see your email. Where did you send to?

**Comment by RaquelVaya** [comment]
Sorry Im going to re-send the data to [yihsiao@umich.edu].

**Comment by hsiaoyi0504** [comment]
Just to document the issue. Users tried to analyze experiment with only one sample for each condition. It basically doesn't support by FragPipe-Analyst since you are not going to be able to calculate variance for each condition.
